MOCK_DATA_EVENTS = [
  {
    "event_name": "UFC Fight Night: Rodriguez vs. Lemos",
    "event_date": "2022-11-05T00:00:00",
    "event_location": "Las Vegas, Nevada, USA",
    "event_url": "http://www.ufcstats.com/event-details/756f45905fb20cb5"
  },
  {
    "event_name": "UFC Fight Night: Kattar vs. Allen",
    "event_date": "2022-10-29T00:00:00",
    "event_location": "Las Vegas, Nevada, USA",
    "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
  },
  {
    "event_name": "UFC 280: Oliveira vs. Makhachev",
    "event_date": "2022-10-22T00:00:00",
    "event_location": "Abu Dhabi, Abu Dhabi, United Arab Emirates",
    "event_url": "http://www.ufcstats.com/event-details/885e7f70dcac0007"
  },
  {
    "event_name": "UFC Fight Night: Grasso vs. Araujo",
    "event_date": "2022-10-15T00:00:00",
    "event_location": "Las Vegas, Nevada, USA",
    "event_url": "http://www.ufcstats.com/event-details/49c29e57d4e2be6f"
  },
]


MOCK_DATA_FIGHTS = [
  {
    "fight_url": "http://www.ufcstats.com/fight-details/86dff1593d8b9a1f",
    "fighter1_name": "Chase Hooper",
    "fighter2_name": "Steve Garcia",
    "winner": "Steve Garcia",
    "division": "Featherweight Bout",
    "win_method": "KO/TKO",
    "win_method_details": "Punches to Head At Distance ",
    "referee": "Herb Dean",
    "end_round": 1,
    "end_second": 92,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 10,
    "f1_total_sigstrikes_a": 30,
    "f1_total_strikes_l": 10,
    "f1_total_strikes_a": 32,
    "f1_total_takedown_l": 0,
    "f1_total_takedown_a": 1,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 0,
    "f2_total_knockdown": 3,
    "f2_total_sigstrikes_l": 29,
    "f2_total_sigstrikes_a": 44,
    "f2_total_strikes_l": 31,
    "f2_total_strikes_a": 46,
    "f2_total_takedown_l": 0,
    "f2_total_takedown_a": 0,
    "f2_total_submission_a": 0,
    "f2_total_pass": 0,
    "f2_total_reversal": 17,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/6a7db3750822d7be",
    "fighter1_name": "Josh Fremd",
    "fighter2_name": "Tresean Gore",
    "winner": "Tresean Gore",
    "division": "Middleweight Bout",
    "win_method": "Submission",
    "win_method_details": "Guillotine Choke In Clinch ",
    "referee": "Chris Tognoni",
    "end_round": 2,
    "end_second": 49,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 24,
    "f1_total_sigstrikes_a": 54,
    "f1_total_strikes_l": 27,
    "f1_total_strikes_a": 57,
    "f1_total_takedown_l": 0,
    "f1_total_takedown_a": 1,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 39,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 10,
    "f2_total_sigstrikes_a": 20,
    "f2_total_strikes_l": 14,
    "f2_total_strikes_a": 25,
    "f2_total_takedown_l": 3,
    "f2_total_takedown_a": 4,
    "f2_total_submission_a": 1,
    "f2_total_pass": 0,
    "f2_total_reversal": 246,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/fdb9d29cf0edc16a",
    "fighter1_name": "Christian Rodriguez",
    "fighter2_name": "Joshua Weems",
    "winner": "Christian Rodriguez",
    "division": "Bantamweight Bout",
    "win_method": "Submission",
    "win_method_details": "Anaconda Choke From Side Control ",
    "referee": "Chris Tognoni",
    "end_round": 1,
    "end_second": 247,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 9,
    "f1_total_sigstrikes_a": 23,
    "f1_total_strikes_l": 15,
    "f1_total_strikes_a": 30,
    "f1_total_takedown_l": 0,
    "f1_total_takedown_a": 2,
    "f1_total_submission_a": 1,
    "f1_total_pass": 0,
    "f1_total_reversal": 56,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 18,
    "f2_total_sigstrikes_a": 26,
    "f2_total_strikes_l": 22,
    "f2_total_strikes_a": 32,
    "f2_total_takedown_l": 2,
    "f2_total_takedown_a": 3,
    "f2_total_submission_a": 0,
    "f2_total_pass": 0,
    "f2_total_reversal": 103,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/a554a72bb0377213",
    "fighter1_name": "Calvin Kattar",
    "fighter2_name": "Arnold Allen",
    "winner": "Arnold Allen",
    "division": "Featherweight Bout",
    "win_method": "KO/TKO",
    "win_method_details": "to At DistanceKnee injury",
    "referee": "Herb Dean",
    "end_round": 2,
    "end_second": 8,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 14,
    "f1_total_sigstrikes_a": 58,
    "f1_total_strikes_l": 14,
    "f1_total_strikes_a": 58,
    "f1_total_takedown_l": 0,
    "f1_total_takedown_a": 0,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 0,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 28,
    "f2_total_sigstrikes_a": 67,
    "f2_total_strikes_l": 28,
    "f2_total_strikes_a": 67,
    "f2_total_takedown_l": 0,
    "f2_total_takedown_a": 0,
    "f2_total_submission_a": 0,
    "f2_total_pass": 0,
    "f2_total_reversal": 23,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/bf59d9f8bd9536f3",
    "fighter1_name": "Tim Means",
    "fighter2_name": "Max Griffin",
    "winner": "Max Griffin",
    "division": "Welterweight Bout",
    "win_method": "Decision - Split",
    "win_method_details": " Ben Cartlidge 28 - 29.Eric Colon 29 - 28.Derek Cleary 27 - 30.",
    "referee": "Dan Miragliotta",
    "end_round": 3,
    "end_second": 300,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 47,
    "f1_total_sigstrikes_a": 115,
    "f1_total_strikes_l": 143,
    "f1_total_strikes_a": 215,
    "f1_total_takedown_l": 3,
    "f1_total_takedown_a": 5,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 127,
    "f2_total_knockdown": 1,
    "f2_total_sigstrikes_l": 42,
    "f2_total_sigstrikes_a": 78,
    "f2_total_strikes_l": 56,
    "f2_total_strikes_a": 96,
    "f2_total_takedown_l": 3,
    "f2_total_takedown_a": 6,
    "f2_total_submission_a": 0,
    "f2_total_pass": 0,
    "f2_total_reversal": 513,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/5b6bdaf89e493674",
    "fighter1_name": "Waldo Cortes-Acosta",
    "fighter2_name": "Jared Vanderaa",
    "winner": "Waldo Cortes-Acosta",
    "division": "Heavyweight Bout",
    "win_method": "Decision - Unanimous",
    "win_method_details": " Ron McCarthy 27 - 30.Junichiro Kamijo 28 - 29.Tony Weeks 28 - 29.",
    "referee": "Mark Smith",
    "end_round": 3,
    "end_second": 300,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 73,
    "f1_total_sigstrikes_a": 158,
    "f1_total_strikes_l": 73,
    "f1_total_strikes_a": 158,
    "f1_total_takedown_l": 0,
    "f1_total_takedown_a": 0,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 3,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 56,
    "f2_total_sigstrikes_a": 138,
    "f2_total_strikes_l": 59,
    "f2_total_strikes_a": 143,
    "f2_total_takedown_l": 0,
    "f2_total_takedown_a": 1,
    "f2_total_submission_a": 0,
    "f2_total_pass": 0,
    "f2_total_reversal": 13,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/44abbf6b947be6de",
    "fighter1_name": "Cody Durden",
    "fighter2_name": "Carlos Mota",
    "winner": "Cody Durden",
    "division": "Flyweight Bout",
    "win_method": "Decision - Unanimous",
    "win_method_details": " Adalaide Byrd 27 - 30.Tony Weeks 28 - 29.Ben Cartlidge 28 - 29.",
    "referee": "Mark Smith",
    "end_round": 3,
    "end_second": 300,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 17,
    "f1_total_sigstrikes_a": 37,
    "f1_total_strikes_l": 51,
    "f1_total_strikes_a": 95,
    "f1_total_takedown_l": 4,
    "f1_total_takedown_a": 8,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 1232,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 12,
    "f2_total_sigstrikes_a": 29,
    "f2_total_strikes_l": 36,
    "f2_total_strikes_a": 62,
    "f2_total_takedown_l": 0,
    "f2_total_takedown_a": 0,
    "f2_total_submission_a": 1,
    "f2_total_pass": 1,
    "f2_total_reversal": 11,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/5dcba156bd13e0c3",
    "fighter1_name": "Andrei Arlovski",
    "fighter2_name": "Marcos Rogerio de Lima",
    "winner": "Marcos Rogerio de Lima",
    "division": "Heavyweight Bout",
    "win_method": "Submission",
    "win_method_details": "Rear Naked Choke ",
    "referee": "Mark Smith",
    "end_round": 1,
    "end_second": 110,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 2,
    "f1_total_sigstrikes_a": 5,
    "f1_total_strikes_l": 3,
    "f1_total_strikes_a": 6,
    "f1_total_takedown_l": 0,
    "f1_total_takedown_a": 0,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 0,
    "f2_total_knockdown": 1,
    "f2_total_sigstrikes_l": 6,
    "f2_total_sigstrikes_a": 11,
    "f2_total_strikes_l": 25,
    "f2_total_strikes_a": 33,
    "f2_total_takedown_l": 0,
    "f2_total_takedown_a": 0,
    "f2_total_submission_a": 1,
    "f2_total_pass": 0,
    "f2_total_reversal": 130,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/f32d918ee06cb83b",
    "fighter1_name": "Phil Hawes",
    "fighter2_name": "Roman Dolidze",
    "winner": "Roman Dolidze",
    "division": "Middleweight Bout",
    "win_method": "KO/TKO",
    "win_method_details": "to At Distance ",
    "referee": "Dan Miragliotta",
    "end_round": 1,
    "end_second": 249,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 11,
    "f1_total_sigstrikes_a": 26,
    "f1_total_strikes_l": 15,
    "f1_total_strikes_a": 31,
    "f1_total_takedown_l": 1,
    "f1_total_takedown_a": 1,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 46,
    "f2_total_knockdown": 1,
    "f2_total_sigstrikes_l": 18,
    "f2_total_sigstrikes_a": 42,
    "f2_total_strikes_l": 29,
    "f2_total_strikes_a": 57,
    "f2_total_takedown_l": 0,
    "f2_total_takedown_a": 0,
    "f2_total_submission_a": 1,
    "f2_total_pass": 0,
    "f2_total_reversal": 2,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/98b7dd0ddc52cffb",
    "fighter1_name": "Dustin Jacoby",
    "fighter2_name": "Khalil Rountree Jr.",
    "winner": "Khalil Rountree Jr.",
    "division": "Light Heavyweight Bout",
    "win_method": "Decision - Split",
    "win_method_details": " Ben Cartlidge 28 - 29.Ron McCarthy 29 - 28.Chris Flores 28 - 29.",
    "referee": "Herb Dean",
    "end_round": 3,
    "end_second": 300,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 120,
    "f1_total_sigstrikes_a": 255,
    "f1_total_strikes_l": 122,
    "f1_total_strikes_a": 257,
    "f1_total_takedown_l": 0,
    "f1_total_takedown_a": 3,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 5,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 85,
    "f2_total_sigstrikes_a": 237,
    "f2_total_strikes_l": 88,
    "f2_total_strikes_a": 241,
    "f2_total_takedown_l": 0,
    "f2_total_takedown_a": 0,
    "f2_total_submission_a": 0,
    "f2_total_pass": 0,
    "f2_total_reversal": 0,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/d6d141afdd31c3f1",
    "fighter1_name": "Joseph Holmes",
    "fighter2_name": "Junyong Park",
    "winner": "Junyong Park",
    "division": "Middleweight Bout",
    "win_method": "Submission",
    "win_method_details": "Rear Naked Choke ",
    "referee": "Chris Tognoni",
    "end_round": 2,
    "end_second": 184,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 20,
    "f1_total_sigstrikes_a": 40,
    "f1_total_strikes_l": 21,
    "f1_total_strikes_a": 42,
    "f1_total_takedown_l": 0,
    "f1_total_takedown_a": 0,
    "f1_total_submission_a": 0,
    "f1_total_pass": 1,
    "f1_total_reversal": 39,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 18,
    "f2_total_sigstrikes_a": 33,
    "f2_total_strikes_l": 48,
    "f2_total_strikes_a": 76,
    "f2_total_takedown_l": 2,
    "f2_total_takedown_a": 4,
    "f2_total_submission_a": 2,
    "f2_total_pass": 0,
    "f2_total_reversal": 437,
    "event": {
      "event_name": "UFC Fight Night: Kattar vs. Allen",
      "event_date": "2022-10-29T00:00:00",
      "event_location": "Las Vegas, Nevada, USA",
      "event_url": "http://www.ufcstats.com/event-details/be5aab761c40ef35"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/2d36e2c10ee349fe",
    "fighter1_name": "Makhmud Muradov",
    "fighter2_name": "Caio Borralho",
    "winner": "Caio Borralho",
    "division": "Middleweight Bout",
    "win_method": "Decision - Unanimous",
    "win_method_details": " Junichiro Kamijo 27 - 30.Vito Paolillo 27 - 30.Clemens Werner 28 - 29.",
    "referee": "Daniel Movahedi",
    "end_round": 3,
    "end_second": 300,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 14,
    "f1_total_sigstrikes_a": 35,
    "f1_total_strikes_l": 76,
    "f1_total_strikes_a": 103,
    "f1_total_takedown_l": 2,
    "f1_total_takedown_a": 2,
    "f1_total_submission_a": 0,
    "f1_total_pass": 1,
    "f1_total_reversal": 444,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 19,
    "f2_total_sigstrikes_a": 32,
    "f2_total_strikes_l": 57,
    "f2_total_strikes_a": 77,
    "f2_total_takedown_l": 1,
    "f2_total_takedown_a": 2,
    "f2_total_submission_a": 2,
    "f2_total_pass": 3,
    "f2_total_reversal": 532,
    "event": {
      "event_name": "UFC 280: Oliveira vs. Makhachev",
      "event_date": "2022-10-22T00:00:00",
      "event_location": "Abu Dhabi, Abu Dhabi, United Arab Emirates",
      "event_url": "http://www.ufcstats.com/event-details/885e7f70dcac0007"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/25f3e4fa781c1c8a",
    "fighter1_name": "Katlyn Chookagian",
    "fighter2_name": "Manon Fiorot",
    "winner": "Manon Fiorot",
    "division": "Women's Flyweight Bout",
    "win_method": "Decision - Unanimous",
    "win_method_details": " David Lethaby 28 - 29.Anders Ohlsson 28 - 29.Vito Paolillo 28 - 29.",
    "referee": "Jason Herzog",
    "end_round": 3,
    "end_second": 300,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 76,
    "f1_total_sigstrikes_a": 286,
    "f1_total_strikes_l": 76,
    "f1_total_strikes_a": 286,
    "f1_total_takedown_l": 0,
    "f1_total_takedown_a": 0,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 0,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 98,
    "f2_total_sigstrikes_a": 279,
    "f2_total_strikes_l": 99,
    "f2_total_strikes_a": 280,
    "f2_total_takedown_l": 1,
    "f2_total_takedown_a": 2,
    "f2_total_submission_a": 0,
    "f2_total_pass": 0,
    "f2_total_reversal": 14,
    "event": {
      "event_name": "UFC 280: Oliveira vs. Makhachev",
      "event_date": "2022-10-22T00:00:00",
      "event_location": "Abu Dhabi, Abu Dhabi, United Arab Emirates",
      "event_url": "http://www.ufcstats.com/event-details/885e7f70dcac0007"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/d325a1483d78ae75",
    "fighter1_name": "Belal Muhammad",
    "fighter2_name": "Sean Brady",
    "winner": "Belal Muhammad",
    "division": "Welterweight Bout",
    "win_method": "KO/TKO",
    "win_method_details": "Punches to Head At Distance ",
    "referee": "Lukasz Bosacki",
    "end_round": 2,
    "end_second": 287,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 80,
    "f1_total_sigstrikes_a": 209,
    "f1_total_strikes_l": 80,
    "f1_total_strikes_a": 209,
    "f1_total_takedown_l": 0,
    "f1_total_takedown_a": 0,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 0,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 58,
    "f2_total_sigstrikes_a": 118,
    "f2_total_strikes_l": 58,
    "f2_total_strikes_a": 118,
    "f2_total_takedown_l": 0,
    "f2_total_takedown_a": 5,
    "f2_total_submission_a": 0,
    "f2_total_pass": 0,
    "f2_total_reversal": 0,
    "event": {
      "event_name": "UFC 280: Oliveira vs. Makhachev",
      "event_date": "2022-10-22T00:00:00",
      "event_location": "Abu Dhabi, Abu Dhabi, United Arab Emirates",
      "event_url": "http://www.ufcstats.com/event-details/885e7f70dcac0007"
    }
  },
  {
    "fight_url": "http://www.ufcstats.com/fight-details/cea6760d7bfbe19b",
    "fighter1_name": "Abubakar Nurmagomedov",
    "fighter2_name": "Gadzhi Omargadzhiev",
    "winner": "Abubakar Nurmagomedov",
    "division": "Welterweight Bout",
    "win_method": "Decision - Unanimous",
    "win_method_details": " Ben Cartlidge 28 - 29.Vito Paolillo 28 - 29.Anders Ohlsson 27 - 30.",
    "referee": "Lukasz Bosacki",
    "end_round": 3,
    "end_second": 300,
    "f1_total_knockdown": 0,
    "f1_total_sigstrikes_l": 40,
    "f1_total_sigstrikes_a": 67,
    "f1_total_strikes_l": 76,
    "f1_total_strikes_a": 104,
    "f1_total_takedown_l": 1,
    "f1_total_takedown_a": 4,
    "f1_total_submission_a": 0,
    "f1_total_pass": 0,
    "f1_total_reversal": 755,
    "f2_total_knockdown": 0,
    "f2_total_sigstrikes_l": 38,
    "f2_total_sigstrikes_a": 99,
    "f2_total_strikes_l": 79,
    "f2_total_strikes_a": 142,
    "f2_total_takedown_l": 1,
    "f2_total_takedown_a": 7,
    "f2_total_submission_a": 0,
    "f2_total_pass": 0,
    "f2_total_reversal": 108,
    "event": {
      "event_name": "UFC 280: Oliveira vs. Makhachev",
      "event_date": "2022-10-22T00:00:00",
      "event_location": "Abu Dhabi, Abu Dhabi, United Arab Emirates",
      "event_url": "http://www.ufcstats.com/event-details/885e7f70dcac0007"
    }
  }
]